#####
name: CycleGan
type: Regression #classifier or Regression
bidirect: False 
regist: True   
noise_level: 1  
port: 6019   
save_root: 'output/Short-term/'   # root directory to save the figure
image_save: 'output/Long-term/pred' # root directory to save the pred image
image_save1: 'output/Long-term/before' # root directory to save the  before image
image_save2: 'output/Long-term/after' # root directory to save the  after image
# lamda weight
Adv_lamda: 1
Cyc_lamda: 10
Corr_lamda: 20
Smooth_lamda: 10
epoch: 0        # starting epoch
n_epochs: 200      # How often do you want to display output images during training
batchSize: 30        # size of the batches
dataroot: 'data/Regression/Short-term'     # root directory of the dataset
val_dataroot: 'data/Regression/Short-term' # root directory of the dataset
checkpoint: 'checkpoint/Regression_Short_best_netG_A2B.pth'  # root directory of the checkpoin
lr: 0.0001 # initial learning rate
decay_epoch: 20            # epoch to start linearly decaying the learning rate to 0
size: 256                # size of the data crop
input_nc: 1         
output_nc: 1                  
cuda: True                
n_cpu: 1

