#####
name: CycleGan
bidirect: False #Unidirectional or bidirectional
regist: True   # With or without registration network
noise_level: 1  #  noise level
port: 6019   #  port parameters
save_root: 'output/Long-term/'
image_save: 'output/Long-term/pred'
image_save1: 'output/Long-term/before'
image_save2: 'output/Long-term/after'
# lamda weight
Adv_lamda: 1
Cyc_lamda: 10
Corr_lamda: 20
Smooth_lamda: 10
epoch: 0        # starting epoch
n_epochs: 200      # How often do you want to display output images during training
batchSize: 30        # size of the batches
dataroot: 'data/Long-term'     # root directory of the dataset
val_dataroot: 'data/Long-term'
checkpoint: 'checkpoint/Long_best_netG_A2B.pth'
#lr: 0.001                   # initial learning rate
lr: 0.0001
decay_epoch: 20            # epoch to start linearly decaying the learning rate to 0
size: 256                # size of the data crop
input_nc: 1         
output_nc: 1                  
cuda: True                
n_cpu: 1

